DROP TABLE IF EXISTS `__CL_COURSE__glossary_texts`;
DROP TABLE IF EXISTS `__CL_COURSE__glossary_definitions`;
DROP TABLE IF EXISTS `__CL_COURSE__glossary_words`;
DROP TABLE IF EXISTS `__CL_COURSE__glossary_word_definitions`;
DROP TABLE IF EXISTS `__CL_COURSE__glossary_text_dictionaries`;
DROP TABLE IF EXISTS `__CL_COURSE__glossary_dictionaries`;
DROP TABLE IF EXISTS `__CL_COURSE__glossary_dictionary_tree`;
DROP TABLE IF EXISTS `__CL_COURSE__glossary_tags`;
DROP TABLE IF EXISTS `__CL_COURSE__glossary_tags_entries`;
